# Created by
# /usr/bin/cfgmaker portstatus@127.0.0.1


### Global Config Options

#  for UNIX
# WorkDir: /home/http/mrtg

#  for Debian
WorkDir: /var/www/portaller/static/mrtg

#  or for NT
# WorkDir: c:\mrtgdata

### Global Defaults

#  to get bits instead of bytes and graphs growing to the right
# Options[_]: growright, bits

EnableIPv6: no

######################################################################
# System: tunlr
# Description: Linux tunlr 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_$
# Contact: root
# Location: Unknown
######################################################################


### Interface 1 >> Descr: 'lo' | Name: 'lo' | Ip: '127.0.0.1' | Eth: 'No Ethernet Id' ###
### The following interface is commented out because:
### * it is a Software Loopback interface
#
# Target[127.0.0.1_lo]: #lo:portstatus@127.0.0.1:
# SetEnv[127.0.0.1_lo]: MRTG_INT_IP="127.0.0.1" MRTG_INT_DESCR="lo"
# MaxBytes[127.0.0.1_lo]: 1250000
# Title[127.0.0.1_lo]: Traffic Analysis for lo -- tunlr
# PageTop[127.0.0.1_lo]: <h1>Traffic Analysis for lo -- tunlr</h1>
#               <div id="sysdetails">
#                       <table>
#                               <tr>
#                                       <td>System:</td>
#                                       <td>tunlr in Unknown</td>
#                               </tr>
#                               <tr>
#                                       <td>Maintainer:</td>
#                                       <td>root</td>
#                               </tr>
#                               <tr>
#                                       <td>Description:</td>
#                                       <td>lo  </td>
#                               </tr>
#                               <tr>
#                                       <td>ifType:</td>
#                                       <td>softwareLoopback (24)</td>
#                               </tr>
#                               <tr>
#                                       <td>ifName:</td>
#                                       <td>lo</td>
#                               </tr>
#                               <tr>
#                                       <td>Max Speed:</td>
#                                       <td>1250.0 kBytes/s</td>
#                               </tr>
#                               <tr>
#                                       <td>Ip:</td>
#                                       <td>127.0.0.1 (localhost)</td>
#                               </tr>
#                       </table>
#               </div>


### Interface 2 >> Descr: 'eth0' | Name: 'eth0' | Ip: '107.170.15.247' | Eth: '04-01-13-55-5a-01' ###
### The following interface is commented out because:
### * has no ifSpeed property
#
Target[127.0.0.1_eth0]: #eth0:portstatus@127.0.0.1:
SetEnv[127.0.0.1_eth0]: MRTG_INT_IP="107.170.15.247" MRTG_INT_DESCR="eth0"
MaxBytes[127.0.0.1_eth0]: 100000000
Title[127.0.0.1_eth0]: Traffic Analysis for eth0 -- portaller
PageTop[127.0.0.1_eth0]: <h1>Traffic Analysis for eth0 -- portaller</h1>